name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: install
        run: npm i

      - name: build
        run: npm run build
        env:
          BASE_PATH: /

      - name: create .nojekyll
        run: touch .output/public/.nojekyll

      - name: create CNAME
        run: echo "fwdr.dev" > .output/public/CNAME

      - name: deploy pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: .output/public
